// Additional enrichment data — ingredients, prep time, vitamins, origin, pairings, etc.
// Keyed by menu-item name (same keys as menuHealthData in page.jsx)

export const menuExtraData = {
	// ─── Burgers ─────────────────────────────────────────────
	"Classic Burger": {
		prepTime: "12-15 min",
		servingSize: "1 burger (220g)",
		spiceLevel: 0,
		dietary: ["Halal-option"],
		ingredients: [
			"Beef patty",
			"Brioche bun",
			"Lettuce",
			"Tomato",
			"Onion",
			"Pickles",
			"Ketchup",
			"Mustard",
		],
		vitamins: [
			{ name: "Iron", pct: 25 },
			{ name: "Vitamin B12", pct: 45 },
			{ name: "Zinc", pct: 30 },
			{ name: "Niacin (B3)", pct: 35 },
		],
		origin:
			"Hamburg, Germany / United States — the modern hamburger became an American icon in the early 1900s, evolving from German-style minced beef dishes.",
		pairsWith: [
			"French Fries",
			"Coleslaw",
			"Milkshake",
			"Iced Tea",
			"Craft Beer",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Cheese Burger": {
		prepTime: "12-15 min",
		servingSize: "1 burger (250g)",
		spiceLevel: 0,
		dietary: [],
		ingredients: [
			"Beef patty",
			"Cheddar cheese",
			"Sesame bun",
			"Lettuce",
			"Tomato",
			"Onion",
			"Pickles",
			"Special sauce",
		],
		vitamins: [
			{ name: "Calcium", pct: 30 },
			{ name: "Vitamin B12", pct: 50 },
			{ name: "Iron", pct: 22 },
			{ name: "Phosphorus", pct: 28 },
		],
		origin:
			"Pasadena, California — credited to Lionel Sternberger who reportedly placed a slice of American cheese on a burger in the late 1920s.",
		pairsWith: ["Onion Rings", "Sweet Potato Fries", "Cola", "Root Beer"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Double Smash Burger": {
		prepTime: "15-18 min",
		servingSize: "1 burger (340g)",
		spiceLevel: 0,
		dietary: [],
		ingredients: [
			"2× Smashed beef patties",
			"American cheese",
			"Potato bun",
			"Caramelized onions",
			"Bread-and-butter pickles",
			"Smash sauce",
		],
		vitamins: [
			{ name: "Iron", pct: 40 },
			{ name: "Vitamin B12", pct: 70 },
			{ name: "Zinc", pct: 50 },
			{ name: "Protein (DV)", pct: 90 },
		],
		origin:
			"United States — the smash technique, pressing beef balls flat on a screaming-hot griddle, became a food-truck sensation in the 2010s.",
		pairsWith: [
			"Loaded Fries",
			"Jalapeño Poppers",
			"Craft IPA",
			"Chocolate Shake",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Veggie Burger": {
		prepTime: "10-12 min",
		servingSize: "1 burger (200g)",
		spiceLevel: 1,
		dietary: ["Vegetarian", "Vegan-option"],
		ingredients: [
			"Black bean patty",
			"Whole-wheat bun",
			"Avocado",
			"Sprouts",
			"Tomato",
			"Red onion",
			"Chipotle aioli",
		],
		vitamins: [
			{ name: "Fiber (DV)", pct: 32 },
			{ name: "Iron", pct: 18 },
			{ name: "Vitamin C", pct: 15 },
			{ name: "Folate", pct: 22 },
		],
		origin:
			"London, England — Gregory Sams created the original VegeBurger in 1982, but plant-based patties date back to Indian and East Asian cuisines for centuries.",
		pairsWith: ["Sweet Potato Fries", "Side Salad", "Lemonade", "Kombucha"],
		bestTimeToEat: "Lunch · Dinner",
	},

	// ─── Pizza ───────────────────────────────────────────────
	"Margherita Pizza": {
		prepTime: "18-22 min",
		servingSize: "1 slice (130g) — 8 slices per pie",
		spiceLevel: 0,
		dietary: ["Vegetarian"],
		ingredients: [
			"Pizza dough",
			"San Marzano tomatoes",
			"Fresh mozzarella",
			"Fresh basil",
			"Extra-virgin olive oil",
			"Sea salt",
		],
		vitamins: [
			{ name: "Calcium", pct: 20 },
			{ name: "Vitamin A", pct: 12 },
			{ name: "Lycopene", pct: 18 },
			{ name: "Vitamin K", pct: 10 },
		],
		origin:
			"Naples, Italy — created in 1889 by pizzaiolo Raffaele Esposito to honor Queen Margherita, using ingredients reflecting the Italian flag: red tomato, white mozzarella, green basil.",
		pairsWith: [
			"Arugula Salad",
			"Garlic Bread",
			"Chianti Wine",
			"Sparkling Water",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Pepperoni Pizza": {
		prepTime: "18-22 min",
		servingSize: "1 slice (140g)",
		spiceLevel: 1,
		dietary: [],
		ingredients: [
			"Pizza dough",
			"Tomato sauce",
			"Mozzarella",
			"Pepperoni",
			"Oregano",
			"Chili flakes",
		],
		vitamins: [
			{ name: "Calcium", pct: 18 },
			{ name: "Vitamin A", pct: 8 },
			{ name: "Iron", pct: 10 },
			{ name: "Sodium (DV)", pct: 28 },
		],
		origin:
			"United States — pepperoni itself is an Italian-American creation. It became the #1 pizza topping in America by the 1950s.",
		pairsWith: ["Buffalo Wings", "Caesar Salad", "Cola", "Light Beer"],
		bestTimeToEat: "Lunch · Dinner · Late Night",
	},
	"BBQ Chicken Pizza": {
		prepTime: "20-25 min",
		servingSize: "1 slice (150g)",
		spiceLevel: 1,
		dietary: [],
		ingredients: [
			"Pizza dough",
			"BBQ sauce",
			"Grilled chicken",
			"Smoked gouda",
			"Red onion",
			"Cilantro",
			"Mozzarella",
		],
		vitamins: [
			{ name: "Protein (DV)", pct: 36 },
			{ name: "Calcium", pct: 22 },
			{ name: "Niacin (B3)", pct: 30 },
			{ name: "Vitamin B6", pct: 18 },
		],
		origin:
			"Beverly Hills, California — invented by chef Ed LaDou at Spago in 1985, later popularized by California Pizza Kitchen.",
		pairsWith: ["Ranch Dip", "Coleslaw", "Iced Tea", "Pale Ale"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Veggie Supreme": {
		prepTime: "20-24 min",
		servingSize: "1 slice (155g)",
		spiceLevel: 0,
		dietary: ["Vegetarian"],
		ingredients: [
			"Pizza dough",
			"Tomato sauce",
			"Mozzarella",
			"Bell peppers",
			"Mushrooms",
			"Black olives",
			"Red onion",
			"Spinach",
			"Artichoke hearts",
		],
		vitamins: [
			{ name: "Vitamin C", pct: 25 },
			{ name: "Vitamin A", pct: 20 },
			{ name: "Iron", pct: 12 },
			{ name: "Potassium", pct: 15 },
		],
		origin:
			"United States — vegetable-loaded pizzas gained popularity during the health-food movement of the 1970s-80s as an alternative to meat-heavy options.",
		pairsWith: [
			"Minestrone Soup",
			"Garlic Knots",
			"Pinot Grigio",
			"Fruit Juice",
		],
		bestTimeToEat: "Lunch · Dinner",
	},

	// ─── Sushi ───────────────────────────────────────────────
	"California Roll": {
		prepTime: "10-12 min",
		servingSize: "8 pieces (185g)",
		spiceLevel: 0,
		dietary: ["Pescatarian"],
		ingredients: [
			"Sushi rice",
			"Nori seaweed",
			"Imitation crab",
			"Avocado",
			"Cucumber",
			"Sesame seeds",
			"Rice vinegar",
		],
		vitamins: [
			{ name: "Iodine", pct: 15 },
			{ name: "Vitamin E", pct: 10 },
			{ name: "Manganese", pct: 22 },
			{ name: "Omega-3 (ALA)", pct: 12 },
		],
		origin:
			"Vancouver, Canada / Los Angeles — chef Hidekazu Tojo claims to have invented the inside-out roll in the 1960s-70s to appeal to North Americans unfamiliar with nori on the outside.",
		pairsWith: ["Edamame", "Miso Soup", "Green Tea", "Sake", "Ginger Ale"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Salmon Nigiri": {
		prepTime: "5-8 min",
		servingSize: "4 pieces (120g)",
		spiceLevel: 0,
		dietary: ["Pescatarian", "Gluten-Free-option"],
		ingredients: [
			"Sushi-grade salmon",
			"Sushi rice",
			"Wasabi",
			"Rice vinegar",
			"Soy sauce",
		],
		vitamins: [
			{ name: "Omega-3 (DHA/EPA)", pct: 60 },
			{ name: "Vitamin D", pct: 80 },
			{ name: "Vitamin B12", pct: 120 },
			{ name: "Selenium", pct: 45 },
		],
		origin:
			"Tokyo, Japan — nigiri-zushi was born in Edo (Tokyo) in the 1820s. Traditionally salmon was not used; Norwegian exporters introduced salmon sushi to Japan in the 1980s-90s.",
		pairsWith: [
			"Miso Soup",
			"Seaweed Salad",
			"Sake",
			"Japanese Beer",
			"Green Tea",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Dragon Roll": {
		prepTime: "12-15 min",
		servingSize: "8 pieces (230g)",
		spiceLevel: 1,
		dietary: ["Pescatarian"],
		ingredients: [
			"Sushi rice",
			"Nori",
			"Shrimp tempura",
			"Avocado (draped)",
			"Cucumber",
			"Eel sauce",
			"Tobiko",
			"Sesame seeds",
		],
		vitamins: [
			{ name: "Omega-3", pct: 20 },
			{ name: "Vitamin E", pct: 18 },
			{ name: "Potassium", pct: 16 },
			{ name: "Vitamin A", pct: 10 },
		],
		origin:
			"United States — a Japanese-American fusion roll that became a sushi-bar staple in the 1990s, named for its dragon-like appearance with avocado scales.",
		pairsWith: ["Seaweed Salad", "Gyoza", "Sake", "Plum Wine"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Spicy Tuna Roll": {
		prepTime: "8-10 min",
		servingSize: "8 pieces (200g)",
		spiceLevel: 3,
		dietary: ["Pescatarian"],
		ingredients: [
			"Sushi rice",
			"Nori",
			"Fresh tuna",
			"Spicy mayo (Sriracha + Kewpie)",
			"Scallions",
			"Sesame seeds",
			"Cucumber",
		],
		vitamins: [
			{ name: "Selenium", pct: 50 },
			{ name: "Niacin (B3)", pct: 40 },
			{ name: "Omega-3", pct: 30 },
			{ name: "Vitamin B6", pct: 25 },
		],
		origin:
			"Los Angeles, California — one of the earliest American-invented maki rolls, created in the 1980s to introduce bolder flavors to Western diners.",
		pairsWith: ["Edamame", "Miso Soup", "Japanese Beer", "Matcha Latte"],
		bestTimeToEat: "Lunch · Dinner",
	},

	// ─── Mexican ─────────────────────────────────────────────
	"Chicken Burrito": {
		prepTime: "10-14 min",
		servingSize: "1 burrito (380g)",
		spiceLevel: 2,
		dietary: ["Halal-option"],
		ingredients: [
			"Flour tortilla",
			"Grilled chicken",
			"Cilantro-lime rice",
			"Black beans",
			"Pico de gallo",
			"Sour cream",
			"Guacamole",
			"Cheese",
			"Lettuce",
		],
		vitamins: [
			{ name: "Protein (DV)", pct: 70 },
			{ name: "Iron", pct: 20 },
			{ name: "Fiber (DV)", pct: 40 },
			{ name: "Vitamin C", pct: 15 },
		],
		origin:
			"Ciudad Juárez, Mexico — legend credits Juan Méndez with wrapping food in a large flour tortilla for portability in the 1910s; the word 'burrito' means 'little donkey.'",
		pairsWith: [
			"Tortilla Chips & Salsa",
			"Horchata",
			"Margarita",
			"Mexican Beer",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Carne Asada Tacos": {
		prepTime: "15-20 min",
		servingSize: "3 tacos (280g)",
		spiceLevel: 2,
		dietary: ["Gluten-Free-option"],
		ingredients: [
			"Corn tortillas",
			"Grilled skirt steak",
			"White onion",
			"Cilantro",
			"Lime",
			"Salsa verde",
			"Radish",
			"Queso fresco",
		],
		vitamins: [
			{ name: "Iron", pct: 30 },
			{ name: "Zinc", pct: 35 },
			{ name: "Vitamin B12", pct: 40 },
			{ name: "Vitamin C", pct: 12 },
		],
		origin:
			"Sonora, Mexico — 'carne asada' (grilled meat) is a tradition across northern Mexico. Street-style tacos de carne asada are a Sonoran staple dating back centuries.",
		pairsWith: [
			"Grilled Corn (Elote)",
			"Refried Beans",
			"Agua Fresca",
			"Tequila",
		],
		bestTimeToEat: "Lunch · Dinner · Late Night",
	},
	"Fish Tacos": {
		prepTime: "12-16 min",
		servingSize: "3 tacos (260g)",
		spiceLevel: 1,
		dietary: ["Pescatarian"],
		ingredients: [
			"Corn tortillas",
			"Battered white fish",
			"Cabbage slaw",
			"Lime crema",
			"Pico de gallo",
			"Avocado",
			"Cilantro",
		],
		vitamins: [
			{ name: "Omega-3", pct: 25 },
			{ name: "Vitamin C", pct: 20 },
			{ name: "Vitamin B12", pct: 30 },
			{ name: "Selenium", pct: 22 },
		],
		origin:
			"Ensenada, Baja California, Mexico — fish tacos originated in the Baja peninsula, where beer-battered fish is a coastal tradition. They migrated to San Diego and spread across the US.",
		pairsWith: ["Chips & Guacamole", "Mexican Rice", "Michelada", "Lime Soda"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Guacamole & Chips": {
		prepTime: "8-10 min",
		servingSize: "1 bowl with chips (180g)",
		spiceLevel: 1,
		dietary: ["Vegan", "Gluten-Free"],
		ingredients: [
			"Ripe avocados",
			"Lime juice",
			"Cilantro",
			"Red onion",
			"Jalapeño",
			"Tomato",
			"Sea salt",
			"Corn tortilla chips",
		],
		vitamins: [
			{ name: "Potassium", pct: 22 },
			{ name: "Vitamin E", pct: 18 },
			{ name: "Vitamin K", pct: 26 },
			{ name: "Folate", pct: 20 },
		],
		origin:
			"Aztec Empire, Mexico — guacamole comes from the Nahuatl word 'āhuacamolli' (avocado sauce). The Aztecs made it as early as the 16th century.",
		pairsWith: ["Salsa Trio", "Quesadilla", "Margarita", "Cerveza"],
		bestTimeToEat: "Anytime · Appetizer",
	},

	// ─── Thai ────────────────────────────────────────────────
	"Pad Thai": {
		prepTime: "12-15 min",
		servingSize: "1 plate (350g)",
		spiceLevel: 2,
		dietary: ["Gluten-Free"],
		ingredients: [
			"Rice noodles",
			"Shrimp or tofu",
			"Bean sprouts",
			"Scrambled egg",
			"Peanuts",
			"Tamarind paste",
			"Fish sauce",
			"Lime",
			"Scallions",
		],
		vitamins: [
			{ name: "Manganese", pct: 25 },
			{ name: "Selenium", pct: 22 },
			{ name: "Niacin (B3)", pct: 18 },
			{ name: "Vitamin C", pct: 10 },
		],
		origin:
			"Thailand — created in the 1930s-40s during Prime Minister Phibunsongkhram's campaign to promote Thai national identity. Rice noodles replaced Chinese wheat noodles.",
		pairsWith: ["Thai Iced Tea", "Spring Rolls", "Tom Kha Gai", "Jasmine Rice"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Green Curry": {
		prepTime: "20-25 min",
		servingSize: "1 bowl with rice (320g)",
		spiceLevel: 4,
		dietary: ["Gluten-Free"],
		ingredients: [
			"Green curry paste",
			"Coconut milk",
			"Chicken or tofu",
			"Thai basil",
			"Thai eggplant",
			"Bamboo shoots",
			"Kaffir lime leaves",
			"Fish sauce",
			"Palm sugar",
		],
		vitamins: [
			{ name: "Vitamin A", pct: 20 },
			{ name: "Vitamin C", pct: 15 },
			{ name: "Iron", pct: 18 },
			{ name: "Manganese", pct: 30 },
		],
		origin:
			"Central Thailand — green curry (แกงเขียวหวาน, gaeng khiao wan) translates to 'sweet green curry.' The green color comes from fresh green chilies, and it's one of the three classic Thai curries.",
		pairsWith: ["Jasmine Rice", "Roti", "Thai Iced Tea", "Lemongrass Water"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Tom Yum Soup": {
		prepTime: "15-20 min",
		servingSize: "1 bowl (280g)",
		spiceLevel: 4,
		dietary: ["Gluten-Free", "Low-Carb"],
		ingredients: [
			"Shrimp",
			"Lemongrass",
			"Galangal",
			"Kaffir lime leaves",
			"Thai chilies",
			"Fish sauce",
			"Lime juice",
			"Mushrooms",
			"Cilantro",
			"Cherry tomatoes",
		],
		vitamins: [
			{ name: "Vitamin C", pct: 30 },
			{ name: "Selenium", pct: 35 },
			{ name: "Iron", pct: 12 },
			{ name: "Vitamin B12", pct: 20 },
		],
		origin:
			"Thailand — tom yum (ต้มยำ) means 'boiled/sour-spicy.' It's one of the world's most famous soups, recognized by UNESCO as part of Thailand's intangible cultural heritage (proposed 2024).",
		pairsWith: [
			"Jasmine Rice",
			"Spring Rolls",
			"Thai Iced Tea",
			"Coconut Water",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Mango Sticky Rice": {
		prepTime: "30-40 min",
		servingSize: "1 plate (220g)",
		spiceLevel: 0,
		dietary: ["Vegan", "Gluten-Free"],
		ingredients: [
			"Glutinous (sticky) rice",
			"Ripe mango",
			"Coconut milk",
			"Palm sugar",
			"Sesame seeds",
			"Pinch of salt",
		],
		vitamins: [
			{ name: "Vitamin A", pct: 25 },
			{ name: "Vitamin C", pct: 60 },
			{ name: "Manganese", pct: 30 },
			{ name: "Folate", pct: 12 },
		],
		origin:
			"Thailand — khao niao mamuang (ข้าวเหนียวมะม่วง) is a beloved Thai dessert served during mango season (April-June). It's a street-food icon across Southeast Asia.",
		pairsWith: ["Thai Iced Tea", "Coconut Ice Cream", "Black Coffee"],
		bestTimeToEat: "Dessert · Afternoon Snack",
	},

	// ─── Indian ──────────────────────────────────────────────
	"Butter Chicken": {
		prepTime: "25-35 min",
		servingSize: "1 bowl with naan (300g)",
		spiceLevel: 2,
		dietary: ["Halal-option"],
		ingredients: [
			"Chicken thighs (tandoori-marinated)",
			"Tomato purée",
			"Butter",
			"Heavy cream",
			"Kasuri methi (fenugreek)",
			"Ginger-garlic paste",
			"Garam masala",
			"Turmeric",
			"Kashmiri chili",
		],
		vitamins: [
			{ name: "Vitamin A", pct: 30 },
			{ name: "Vitamin B12", pct: 25 },
			{ name: "Iron", pct: 15 },
			{ name: "Vitamin C", pct: 12 },
		],
		origin:
			"Delhi, India — invented in the 1950s at Moti Mahal restaurant by Kundan Lal Gujral. Leftover tandoori chicken was simmered in a rich tomato-butter gravy, creating one of the world's most loved curries.",
		pairsWith: [
			"Garlic Naan",
			"Basmati Rice",
			"Raita",
			"Mango Lassi",
			"Masala Chai",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Palak Paneer": {
		prepTime: "20-28 min",
		servingSize: "1 bowl with roti (280g)",
		spiceLevel: 1,
		dietary: ["Vegetarian", "Gluten-Free-option"],
		ingredients: [
			"Fresh spinach",
			"Paneer cheese",
			"Onion",
			"Tomato",
			"Ginger-garlic paste",
			"Green chili",
			"Cumin",
			"Garam masala",
			"Cream",
		],
		vitamins: [
			{ name: "Vitamin A", pct: 90 },
			{ name: "Vitamin K", pct: 400 },
			{ name: "Iron", pct: 35 },
			{ name: "Calcium", pct: 40 },
		],
		origin:
			"Punjab, India — palak (spinach) paneer is a staple of Punjabi cuisine dating back centuries. Paneer-making in India traces to the Mughal era and Portuguese influence.",
		pairsWith: ["Butter Naan", "Jeera Rice", "Raita", "Lassi"],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Chicken Biryani": {
		prepTime: "40-55 min",
		servingSize: "1 plate (400g)",
		spiceLevel: 3,
		dietary: ["Halal-option"],
		ingredients: [
			"Basmati rice",
			"Chicken (bone-in)",
			"Yogurt marinade",
			"Saffron",
			"Fried onions (birista)",
			"Ghee",
			"Whole spices (cardamom, cloves, bay leaf)",
			"Ginger-garlic",
			"Mint",
			"Rose water",
		],
		vitamins: [
			{ name: "Protein (DV)", pct: 56 },
			{ name: "Iron", pct: 18 },
			{ name: "Vitamin B6", pct: 25 },
			{ name: "Manganese", pct: 40 },
		],
		origin:
			"Hyderabad / Lucknow, India — biryani arrived in India through Mughal rulers (16th-17th century). The Hyderabadi 'dum' style layers raw marinated meat with parboiled rice and slow-cooks it sealed.",
		pairsWith: [
			"Mirchi Ka Salan",
			"Raita",
			"Gulab Jamun",
			"Masala Chai",
			"Rooh Afza",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	Samosa: {
		prepTime: "25-35 min",
		servingSize: "2 pieces (140g)",
		spiceLevel: 2,
		dietary: ["Vegetarian", "Vegan-option"],
		ingredients: [
			"All-purpose flour dough",
			"Potato",
			"Green peas",
			"Cumin",
			"Coriander",
			"Garam masala",
			"Green chili",
			"Amchur (dried mango powder)",
		],
		vitamins: [
			{ name: "Potassium", pct: 12 },
			{ name: "Vitamin C", pct: 10 },
			{ name: "Vitamin B6", pct: 15 },
			{ name: "Iron", pct: 8 },
		],
		origin:
			"Central Asia → India — the samosa (from the Persian 'sanbosag') traveled the Silk Road to India around the 13th-14th century. Today it's India's most iconic street food.",
		pairsWith: [
			"Mint Chutney",
			"Tamarind Chutney",
			"Masala Chai",
			"Chole (Chickpea Curry)",
		],
		bestTimeToEat: "Snack · Tea Time · Appetizer",
	},

	// ─── Mediterranean ───────────────────────────────────────
	"Chicken Shawarma": {
		prepTime: "20-30 min",
		servingSize: "1 wrap (320g)",
		spiceLevel: 1,
		dietary: ["Halal"],
		ingredients: [
			"Chicken thigh (marinated)",
			"Pita bread",
			"Garlic toum",
			"Pickled turnip",
			"Tahini sauce",
			"Lettuce",
			"Tomato",
			"Sumac",
			"Cumin",
			"Turmeric",
		],
		vitamins: [
			{ name: "Protein (DV)", pct: 64 },
			{ name: "Vitamin B6", pct: 35 },
			{ name: "Niacin (B3)", pct: 40 },
			{ name: "Iron", pct: 15 },
		],
		origin:
			"Ottoman Empire (modern Turkey/Levant) — shawarma derives from the Turkish 'çevirme' (turning). Meat stacked on a vertical spit was adopted across the Middle East, each region adding its own spice blend.",
		pairsWith: ["Hummus", "Tabbouleh", "Pickles", "Ayran", "Mint Lemonade"],
		bestTimeToEat: "Lunch · Dinner · Late Night",
	},
	"Falafel Plate": {
		prepTime: "20-25 min",
		servingSize: "6 pieces + sides (350g)",
		spiceLevel: 1,
		dietary: ["Vegan", "Halal"],
		ingredients: [
			"Chickpeas (soaked, not canned)",
			"Fresh parsley",
			"Fresh cilantro",
			"Onion",
			"Garlic",
			"Cumin",
			"Coriander",
			"Baking powder",
			"Tahini sauce",
			"Pickled veggies",
		],
		vitamins: [
			{ name: "Fiber (DV)", pct: 48 },
			{ name: "Iron", pct: 30 },
			{ name: "Folate", pct: 35 },
			{ name: "Manganese", pct: 40 },
		],
		origin:
			"Egypt / Levant — falafel likely originated as ta'amiya in Egypt (made with fava beans). The chickpea version spread through the Levant and became a beloved street food worldwide.",
		pairsWith: [
			"Pita Bread",
			"Hummus",
			"Tabbouleh",
			"Pickled Turnips",
			"Mint Tea",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Lamb Kofta": {
		prepTime: "20-25 min",
		servingSize: "4 skewers (260g)",
		spiceLevel: 2,
		dietary: ["Halal", "Gluten-Free-option"],
		ingredients: [
			"Ground lamb",
			"Onion (grated)",
			"Fresh parsley",
			"Fresh mint",
			"Cumin",
			"Coriander",
			"Paprika",
			"Cinnamon",
			"Garlic",
			"Pine nuts (optional)",
		],
		vitamins: [
			{ name: "Iron", pct: 30 },
			{ name: "Zinc", pct: 40 },
			{ name: "Vitamin B12", pct: 55 },
			{ name: "Selenium", pct: 25 },
		],
		origin:
			"Persia / Middle East — kofta (from Persian 'kūfta,' meaning pounded) has been prepared across the Middle East, South Asia, and the Balkans for over a thousand years.",
		pairsWith: [
			"Tzatziki",
			"Grilled Vegetables",
			"Pita",
			"Tabbouleh",
			"Red Wine",
		],
		bestTimeToEat: "Lunch · Dinner",
	},
	"Hummus Plate": {
		prepTime: "10-15 min",
		servingSize: "1 plate (250g)",
		spiceLevel: 0,
		dietary: ["Vegan", "Gluten-Free-option", "Halal"],
		ingredients: [
			"Chickpeas",
			"Tahini",
			"Lemon juice",
			"Garlic",
			"Extra-virgin olive oil",
			"Cumin",
			"Paprika",
			"Pita bread",
			"Parsley",
		],
		vitamins: [
			{ name: "Fiber (DV)", pct: 32 },
			{ name: "Iron", pct: 22 },
			{ name: "Folate", pct: 30 },
			{ name: "Phosphorus", pct: 20 },
		],
		origin:
			"Levant / Middle East — hummus (Arabic for 'chickpeas') appears in 13th-century Egyptian cookbooks. Today, it's claimed by Lebanon, Israel, Palestine, Syria, and beyond as a national dish.",
		pairsWith: [
			"Falafel",
			"Pita Bread",
			"Olives",
			"Fresh Vegetables",
			"Mint Tea",
			"Arak",
		],
		bestTimeToEat: "Anytime · Appetizer · Snack",
	},
};

// Default extra data for items not in the map
export const defaultExtraData = {
	prepTime: "15-20 min",
	servingSize: "1 serving",
	spiceLevel: 1,
	dietary: [],
	ingredients: ["Please check with the restaurant for full ingredients list"],
	vitamins: [{ name: "Varies", pct: 0 }],
	origin: "Origin information coming soon.",
	pairsWith: ["Check with restaurant for pairing suggestions"],
	bestTimeToEat: "Lunch · Dinner",
};
